version: '3'
services:
  app:
    restart: always
    build:
      context: .
    container_name: ror-service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/webapp
    ports:
      - 4000:4000